### ISSUE TITLE
Ability to specify containing element of Tooltip

### ISSUE THREAD

**Issue by TristanBrotherton** [themesberg/flowbite-svelte#732] opened 2023-05-05 19:33 UTC
Sometimes you will have a tooltip inside a container that has overflow-hidden. It would be useful to be able to specify the element the tooltip can bind to - like body, so that it can display correctly outside of the element with hidden overflow.

**Comment by jjagielka** [comment] 2023-05-05 19:47
`Tooltip` can be put anywhere in the document. Use the `triggeredBy` property to `bind` it with controlling element.
```svelte
<body>
<main>
  <Button id="button">Show tooltip</Button>
</main>
<Tooltip triggeredBy="#button">Text</Tooltip>
</body>

**Comment by TristanBrotherton** [comment] 2023-05-05 22:07
Unfortunately that often creates other issues. For example its often required to have the tooltip rendered inside of an if statement or conditional logic, if the tooltip is placed elsewhere it looses its connection to the element that it should be triggeredBy. To work around that you would have to have identical logic in both places. A much better solution would be to include the tooltip in the same logic, so and be able to specify where you want it to render.

**Comment by jjagielka** [comment] 2023-05-06 10:18
OK. Fair enough.
Back to your question, can you please create a [REPL](https://svelte.dev/repl) with the case causing the issue? I've played a bit with `overflow-hidden` but I can't reproduce the issue.

**Comment by TristanBrotherton** [comment] 2023-05-11 17:08
@jjagielka can you point me in the correct direction to getting the REPL setup with flowbite svelte? - This is my work in progress, but as you can see the Tooltip will not hide and errors: https://svelte.dev/repl/8a4ce244ffdd4f7a98a2dad5d5e892ad?version=3.59.1

**Comment by TristanBrotherton** [comment] 2023-05-11 19:01
@jjagielka I'm trying to create a REPL for you, but using [your template](https://svelte.dev/repl/d581682614a7436097bda1343c770f38?version=3.59.1), I get an error rendering the tooltip. 

Conceptually though its really simple, a tooltip can't display inside a container if it has `overflow:hidden` as it can't overflow it. Thats why we need the ability to set the containing element. (Which is already an option in Popper.js so its just a matter of exposing the prop).

**Comment by jjagielka** [comment] 2023-05-13 13:30
> (Which is already an option in Popper.js so its just a matter of exposing the prop).

@TristanBrotherton  Which option do you have in mind?

**Comment by TristanBrotherton** [comment] 2023-05-15 19:58
I was incorrect, it was another popper.js that allowed the specification of the HTML element. The one implemented here, from the best of my comprehension does not.  It could be implemented by exposing a prop:

```
    /**
     * The target element the popper should be appended to.
     * If not provided, the popper is appended to nearest simbling
     *
     * @type {HTMLElement}
     */
    export let target: HTMLElement = document.body;
```
    
    and in popper:
    
```
        onMount(() => {
        if (!target) {
            target = document.body;
        }
        if (target) {
            target.appendChild(ref);
        }
    });
```

**Comment by TristanBrotherton** [comment] 2023-05-19 17:21
Another issue that makes this even more important is you can't specify a z-index for the tooltip as you are using a 3d transformation already which means the z-index is ignored.

https://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d

**Comment by shinokada** [comment] 2023-09-08 15:40
I close the issue for now since we have updated API.
Please feel free to open a new issue.
Thank you for your contribution.

**Closed by shinokada** 2023-09-08 15:40 UTC
Labels: enhancement
