### ISSUE TITLE
Multiselect Broken

### ISSUE THREAD

**Issue by DavidWhit** [themesberg/flowbite-svelte#1411] opened 2024-08-12 22:41 UTC
### Describe the bug

MultiSelect fails to add or change the values after an additional value/name Object is added to the array.  

Taken from the **docs** and added  { value: "bb", name: "Pan" },  appears to break functionality.

I then discovered all my Multiselects in my project are non functional now.

### Reproduction

```
<script>
  import { MultiSelect } from 'flowbite-svelte';

  let selected = []
  let countries = [
    { value: "us", name: "United States" },
    { value: "ca", name: "Canada" },
    { value: "fr", name: "France" },
    { value: "jp", name: "Japan" },
    { value: "en", name: "England" },
    { value: "bb", name: "Pan" },
  ];
</script>

<MultiSelect items={countries} bind:value={selected} />
```

### Flowbite version and System Info

```shell
You can use the defaults in the stackblitz template that one is on 0.46.14 but I've also tried the latest "flowbite-svelte": "^0.46.15". I
```

**Comment by ProtonBeamCannon** [comment] 2024-08-15 00:25
Hi @DavidWhit  I have this problem also and I have created a stackblitz to test this. I think it doesnt work with certain browser which in my case it is Chrome (However i am not 100% certain on this) and only when it's more than 5 objects. I tested this with multiple browser and only doesnt work with chrome however on my other laptop using chrome this problem doesnt occur even if there are more than 5 items. Two of my user also cant use multiselect and one of them using Chrome (the other one is not confirmed).

I created this stackblitz demo to test this. And it only doesnt work with Chrome browser AND having more than 5 items.

[Multi Select bug demo](https://stackblitz.com/edit/sveltejs-kit-template-default-hnm1tv?file=README.md)

@jumtp I tried to recreate this bug however the results differ from my two computers thus it took me so long to go to the issues even though you told me to create an issue ticket. Sorry about this!

**Comment by jumtp** [comment] 2024-08-15 01:46
I just tested it through chrome, and there is no problem here, maybe Influenced by plugin?

**Comment by ProtonBeamCannon** [comment] 2024-08-15 21:29
I tried to deactivate all the plugins and the result is still the same.
Here is my screenshot, did i do right?
![image](https://github.com/user-attachments/assets/7d951376-45bd-4a02-bbfa-1d2ecfe9a4c4)

**Comment by ProtonBeamCannon** [comment] 2024-08-15 21:40
Update 2: 
I manage to put the items in the multiselect if I use $0.click() to open the list instead of clicking it with a mouse to open the list (the list immidietly closed when i try to click the items), i dont understand what is the difference
![image](https://github.com/user-attachments/assets/be4c6972-ab24-4dbe-bc14-de0bbc83858e)

**Comment by DavidWhit** [comment] 2024-08-15 21:50
There is definitely an issue. I’ve opted to roll my own in shadcn svelte
(willing to share if interested). I’m sure it was something simple but I
love and prefer the low level control over my components.

**Comment by ProtonBeamCannon** [comment] 2024-08-15 22:06
Sure, I would love to have it thanks! but also can you confirm if you are using Chrome and using other browser this problem doesnt occur? at this point I'm very curious to find out how the bug occur

**Comment by DavidWhit** [comment] 2024-08-16 03:23
Yes, sorry, latest version of chrome. I can spend some time tomorrow
looking at it under the hood as well.

**Comment by jumtp** [comment] 2024-08-16 04:42
> Update 2: I manage to put the items in the multiselect if I use $0.click() to open the list instead of clicking it with a mouse to open the list (the list immidietly closed when i try to click the items), i dont understand what is the difference ![image](https://private-user-images.githubusercontent.com/109364226/358403013-be4c6972-ab24-4dbe-bc14-de0bbc83858e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxNDIsIm5iZiI6MTcyMzc4Mjg0MiwicGF0aCI6Ii8xMDkzNjQyMjYvMzU4NDAzMDEzLWJlNGM2OTcyLWFiMjQtNGRiZS1iYzE0LWRlMGJiYzgzODU4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDM0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTlkMzdjZmE3MzFjODA5YWI5MDFhMjYyMjQyYWFlZDExOGExOWRlZDQ4YWYyZGMzMTBjNmU4ZjQ3ZjE4ZDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pA6FmAWB2eLins58Ao8ucWf-g9TJJchUeKRuCKtnZN8)

Did you do this using a buggy browser? If so, i guess there should be a problem with click event.Maybe click div & click outside & click item is trigger at the same time,

**Comment by ProtonBeamCannon** [comment] 2024-08-16 05:06
What do you mean the buggy browser? Do you mean the browser where the bug occured ? Then yes I used the same one, the same chrome without any extension
 >Maybe click div & click outside & click item is trigger at the same time,
 
It does close when i click inside of the multiselect option as if i am selecting outside of the multiselect, like the focus on the dropdown doesnt work,  right click is also the same

**Comment by jumtp** [comment] 2024-08-16 06:06
> What do you mean the buggy browser? Do you mean the browser where the bug occured ? Then yes I used the same one, the same chrome without any extension
> 
> > Maybe click div & click outside & click item is trigger at the same time,
> 
> It does close when i click inside of the multiselect option as if i am selecting outside of the multiselect, like the focus on the dropdown doesnt work, right click is also the same

Yes.I mean The browser where the bug occured. Now we can confirm that your browser is having issues with click events.I think my guess is correct.

You mentioned in my PR before that "more than 5 elements cannot be displayed".Through the test steps I gave you, you can see that the members have been rendered in the DOM but you cannot display them, so I speculate that there is something wrong with the browsing click event.

**Comment by ProtonBeamCannon** [comment] 2024-08-16 06:22
>"more than 5 elements cannot be displayed"

yes this has been consistent and it is also the same as the @DavidWhit first case.

> you can see that the members have been rendered in the DOM but you cannot display them, so I speculate that there is something wrong with the browsing click event.

weird that this only happens with some chrome, is this fixable ?

**Comment by jumtp** [comment] 2024-08-16 07:56
> weird that this only happens with some chrome, is this fixable ?

There is clearly a need to test click events on specific versions of Chrome, and I can only suggest that you ask your users to upgrade their browsers. Because these special versions of chrome are a small part, and normal chrome is the majority. Updating the code for these few errors may cause most errors. It is a nightmare for the authors who maintain this library.

## I have some suggestions
1. This error is that when clicking on the outer div, the 'clickOutSide event is triggered that should not be triggered.
2. So after you fork a piece of code, test around this part, find the reason and customize it for yourself. Might be a good choice.

**Comment by ProtonBeamCannon** [comment] 2024-08-19 18:30
@jumtp i got more info for the user and his problem happens in chrome his version and my version is this one:
Chrome is up to date
Version 127.0.6533.120 (Official Build) (64-bit)

Is your version this one ?

Also @DavidWhit do you have the alternative ? Can I have it please, idk how to fix this issue
>There is definitely an issue. I’ve opted to roll my own in shadcn svelte
(willing to share if interested). I’m sure it was something simple but I
love and prefer the low level control over my components.
I dont know how to fix this one

**Comment by DavidWhit** [comment] 2024-08-19 19:31
Yeah, but it's unrelated to this project. It's based on shadcn-svelte. I didn't get a chance to look at this Friday; honestly not sure I'll have time this week. I really don't think it's a massive change as it worked before.  Anyway if you know about shadcn and ui primitives as well that it fits your project here is a quick and dirty gist. 

https://gist.github.com/DavidWhit/e47d6104eb36008ad530583c03835d21

**Comment by jumtp** [comment] 2024-08-24 18:11
> Is your version this one ?

I got chrome version 127.0.6533.120 from this [website](https://google-chrome.en.uptodown.com/windows/download/1021773178) 

I disabled the chrome automatic update service for testing and everything worked fine under 127.0.6533.120. Maybe the problem lies elsewhere? Or maybe it's because I downloaded the version from the wrong source.

![image](https://github.com/user-attachments/assets/f1019248-578a-43e2-999d-125fc27205c2)
你们的客户或许应该升级一下chrome？我在一个页面中看到chrome的版本分布 
![image](https://github.com/user-attachments/assets/2a9c9cfa-bc83-4fc1-ac07-efef76e7e6f5)

**Comment by jumtp** [comment] 2024-08-26 07:30
> @jumtp It worked now! I don't know why but it works with my chrome browser now

Maybe it's because they use a [browser extension](https://chromewebstore.google.com/category/extensions?utm_source=ext_sidebar&hl=en)

**Comment by cameront** [comment] 2024-08-26 16:56
> @DavidWhit @cameront Can you check if multiselect is still broken in chrome with this stackblitz https://stackblitz.com/edit/sveltejs-kit-template-default-hnm1tv?file=README.md

The first multiselect works for me, the 2nd one doesn't. (I can open the multiselect choices, but selecting one doesn't seem to be a nop)

**Comment by DavidWhit** [comment] 2024-08-28 04:04
Yeah seems to be ok again. Some of the old stuff I had sitting around was also back to normal without redeploying anything. What a nightmare to track. Hats off to maintainers that deal with this.

**Comment by ProtonBeamCannon** [comment] 2024-08-29 22:07
@DavidWhit @jumtp should we close it then ?

**Comment by DavidWhit** [comment] 2024-08-30 04:51
Yeah I'm good. Thanks, all

**Comment by jumtp** [comment] 2024-08-30 04:56
If the problem has been solved, the author can just close this thread.

**Closed** 2024-08-30 11:35 UTC
