### ISSUE TITLE
tooltip positions failes on flex wrapper

### ISSUE THREAD

**Issue by Cluster2a** [themesberg/flowbite-svelte#137] opened 2022-07-09 13:51 UTC
**Describe the bug**
I made a quick video that shows the problem:
https://user-images.githubusercontent.com/84905165/178108568-a72b5bb4-6470-419a-a54c-d2a9225eb6b6.mp4

After hovering the tooltip element the third time the position seems to be fine. The first two hovers are placing the tooltip on different positions.

**To Reproduce**

1. Put a wrapper with flex around your tooltip
2. move cursor on tooltip
3. leave tooltip
4. move cursor again on tooltip

**Code samples**
```html
<div class="p-4 border-t-2 border-gray-700 mt-4 pt-3 flex items-center justify-between">
	<Tooltip content={$LL.components.navigation.meta.helpIcon.tooltip()} placement="auto">
		<span>test</span>
	</Tooltip>
</div>
```

**Expected behavior**
The position should be always the same when hovering the tooltip

**Screenshots**
see video

**Desktop (please complete the following information):**

- Browser: chrome
- Version: 102.0.5005.115

**Comment by shinokada** [comment] 2022-07-16 16:31
Thank you for the issue.
I'm not able to reproduce the problem.

[REPL](https://svelte.dev/repl/8bc0e0d88ec242db868d8e53b765e3bd?version=3.49.0)

Am I missing something here?

**Comment by Cluster2a** [comment] 2022-07-16 17:27
> Thank you for the issue. I'm not able to reproduce the problem.
> 
> [REPL](https://svelte.dev/repl/8bc0e0d88ec242db868d8e53b765e3bd?version=3.49.0)
> 
> Am I missing something here?

You are right - the problem seems to be somehow related to another part of my app. I will investigate a bit more and give you feedback. Thanks a lot!

**Comment by shinokada** [comment] 2022-08-02 20:31
I close the issue for now.
Thank you for your contribution.

**Closed by shinokada** 2022-08-02 20:31 UTC
Labels: bug
