### ISSUE TITLE
Popover do not close without focus

### ISSUE THREAD

**Issue by Chimildic** [themesberg/flowbite-svelte#977] opened 2023-08-10 18:33 UTC
### Describe the bug

Possible, popover has bug with `hideHandler()`. But I dont sure because dont know all cases.

### Reproduction

For example, we have popover in click-mode and complex reference element (long tree) with input field. 

After click on trigger button, popover has focus. Now we click on input field inside reference element. Occurs `focusout` event, according current condition in `hideHandler()`, popover will not close. From now, any click on any places will not close popover. We need to click on popover in order to return focus so that outside click closed him as expected.

If remove `referenceEl` from condition `focusout`, popover will close when focus lost.
```js
// hideHandler()
// now
const elements = [referenceEl, floatingEl, ...triggerEls].filter(Boolean)
// fix
const elements = [floatingEl, ...triggerEls].filter(Boolean)
```

### Flowbite version and System Info

```shell
flowbite-svelte: ^0.42.0
svelte: ^3.44.0 => 3.59.2
vite: ^2.9.13 => 2.9.16
```

**Comment by jjagielka** [comment] 2023-08-11 05:40
I can't reproduce that. [REPL](https://svelte.dev/repl/a056bd49e0b64bf0a4505952e8257883?version=4.1.2) 
Scenario: click button -> click input -> click away

**Comment by jjagielka** [comment] 2023-08-11 06:22
OK. I see. That's tricky one. I'll have a look as your fix proposed has side effects in normal scenarios i.e. without external reference.

**Comment by jjagielka** [comment] 2023-08-11 09:46
I have issued a PR. When it's merged, please do the thorough testing.

**Closed** 2023-08-11 13:36 UTC

**Comment by Chimildic** [comment] 2023-08-13 04:32
In my case I am forced to add `mousedown` event in your fix places. Because click on input or button inside reference did not close popover. Possible it depend on use case.
```
referenceEl.addEventListener('mousedown', () => open = false)
```
