### ISSUE TITLE
Closing modal changes <body> overflow style

### ISSUE THREAD

**Issue by trippjoe** [themesberg/flowbite-svelte#445] opened 2022-11-23 03:47 UTC
### Describe the bug

Closing a modal in my app updates the overflow style of the <body> tag.
Initially the <body> doesn't have an overflow style specified.
When modal opens the body overflow is set to hidden.
When modal closes the body overflow is set to auto.

### Reproduction

TBD.

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 8.80 GB / 15.91 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.52)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    flowbite-svelte: ^0.26.16 => 0.26.16
    svelte: ^3.49.0 => 3.49.0
    vite: ^2.9.14 => 2.9.14
```

**Comment by jjagielka** [comment] 2022-11-23 06:10
By `body` do you mean page body (`document.body`)?

**Comment by trippjoe** [comment] 2022-11-23 18:47
I mean the `<body>`, pretty sure that's the same thing as `document.body`.

**Comment by jjagielka** [comment] 2022-11-23 19:18
Yes, `<body>` and `document.body` relates to the same element.
However I'm not able to reproduce the issue. Are you able to attach the screencast of the scenario?

**Comment by jjagielka** [comment] 2022-12-08 10:50
Is that still an issue?

**Comment by trippjoe** [comment] 2022-12-08 13:00
My bad, I've been meaning to send a video of it just been fairly busy.

**Comment by shinokada** [comment] 2022-12-26 02:43
I close the issue for now.
Thank you for your contribution.
Feel free to open a new issue.

**Closed by shinokada** 2022-12-26 02:43 UTC
