### ISSUE TITLE
Tooltip Breaks App - SSR Sveltekit & Vercel

### ISSUE THREAD

**Issue by enesbala5** [themesberg/flowbite-svelte#592] opened 2023-03-01 10:46 UTC
### Describe the bug

I get an undocumented error (happens sometimes in Vite Preview and 99.99% of times in Vercel) when using Tooltip which causes HMR Reload Error. 

All dependencies are installed. I am guessing this is an error in Popper.js - maybe a if (browser) would fix it, but I am not sure.

Usage:
```
import { Tooltip } from 'flowbite-svelte';

<Tooltip
    triggeredBy=".passwordInput"
    placement="right"
    class="bg-neutral-50 dark:bg-neutral-800"
    >
    <ul class="list-inside list-disc text-sm">
        <li
	    class={password !== undefined && password.length > 7
	    ? 'text-green-600 marker:text-green-600 dark:text-green-400 dark:marker:text-green-400'
	    : 'text-neutral-600 dark:text-neutral-300'}
	>
	    At least 8 characters (and up to 100 characters)
	</li>
	<li
	    class={password !== undefined && password.toUpperCase() != password
	    ? 'text-green-600 marker:text-green-600 dark:text-green-400 dark:marker:text-green-400'
	    : 'text-neutral-600 dark:text-neutral-300'}
	>
	    At least one lowercase character
	</li>
    </ul>
</Tooltip>
```

### Reproduction

```
<script lang="ts">
	import { Tooltip } from 'flowbite-svelte';

	let password: string | undefined = undefined;
</script>

<div class="p-8">
	<input
		class="mt-4 passwordInput"
		bind:value={password}
		name="password"
		type="text"
		title="Password"
		required
	/>

	<Tooltip
		triggeredBy=".passwordInput"
		placement="right"
		class="bg-neutral-50 dark:bg-neutral-800"
	>
		<ul class="list-inside list-disc text-sm">
			<li
				class={password !== undefined && password.length > 7
					? 'text-green-600 marker:text-green-600 dark:text-green-400 dark:marker:text-green-400'
					: 'text-neutral-600 dark:text-neutral-300'}
			>
				At least 8 characters (and up to 100 characters)
			</li>
			<li
				class={password !== undefined && password.toUpperCase() != password
					? 'text-green-600 marker:text-green-600 dark:text-green-400 dark:marker:text-green-400'
					: 'text-neutral-600 dark:text-neutral-300'}
			>
				At least one lowercase character
			</li>
		</ul>
	</Tooltip>
</div>
```

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 1.18 GB / 7.96 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (109.0.1518.70)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @popperjs/core: ^2.11.6 => 2.11.6
    @sveltejs/kit: ^1.8.3 => 1.8.4
    flowbite-svelte: ^0.30.5 => 0.30.5
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.0.1 => 4.1.4
```

**Comment by shinokada** [comment] 2023-06-03 07:43
<img width="600" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/147320/7cf47fdd-7939-4453-af84-15331bd3e121">

I can't reproduce the error.
Can you tell me more details?

**Comment by shinokada** [comment] 2023-06-21 23:46
I am closing this issue for now. Thank you for your contribution! Please feel free to open a new issue if you have any further questions or concerns.

**Closed by shinokada** 2023-06-21 23:46 UTC
